# Generated by Django 5.0.7 on 2024-10-10 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0003_medicinecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicineCategory',
            new_name='Category',
        ),
    ]
