# Generated by Django 5.0.7 on 2024-10-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0004_rename_medicinecategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='brand',
        ),
    ]
