# Generated by Django 5.0.7 on 2024-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0005_remove_medicine_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='auth_user',
            field=models.BooleanField(default=False),
        ),
    ]
