# Generated by Django 5.0.7 on 2024-11-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0007_remove_feedback_product_remove_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalstoreapp.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
