# Generated by Django 5.0.7 on 2024-11-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0021_rename_cartitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='medicine',
            new_name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='medicalstoreapp.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
