# Generated by Django 5.0.7 on 2024-11-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0025_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_n0',
            field=models.CharField(default=17, max_length=10),
            preserve_default=False,
        ),
    ]
