# Generated by Django 5.0.7 on 2024-11-24 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0028_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_gateway',
            new_name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='medicalstoreapp.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default=17, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
