# Generated by Django 5.1.3 on 2024-12-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0033_rename_postal_code_address_zip_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
