# Generated by Django 5.1.3 on 2024-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0035_rename_created_on_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('CARD', 'Credit Card')], default=5, max_length=20),
            preserve_default=False,
        ),
    ]
