# Generated by Django 5.1.3 on 2024-12-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0043_remove_order_user_alter_medicine_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='stock_quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
