# Generated by Django 5.1.3 on 2025-01-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstoreapp', '0054_remove_prescription_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='initiated', max_length=20),
        ),
    ]
